version: '3.5'

services:
  api:
    image: movie-list/api
    container_name: movie-list-api
    build:
      context: ./
    volumes:
      - ./:/code
    networks:
      - movie-list
  http:
    image: nginx:1
    container_name: movie-list-http
    volumes:
      - ./:/code
      - ./host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - movie-list
    depends_on:
      - api

networks:
  movie-list:
